conn LAB1/LAB111

ALTER TABLE PROFESOR
DROP COLUMN CURSO;

ALTER TABLE PROFESOR
DROP CONSTRAINT FK_PROFESOR_CURSO;

ALTER TABLE PROFESOR ADD CURSO VARCHAR2(5) NULL;

ALTER TABLE PROFESOR ADD CONSTRAINT FK_PROFESOR_CURSO
FOREIGN KEY(CURSO)
REFERENCES CURSO(CODIGO);